### ISSUE TITLE
Error on commitMutation updater

### ISSUE THREAD

**Issue by julioxavierr** [julioxavierr/entria-challenge#2]
https://github.com/julioxavierr/entria-challenge/blob/463251c6825429dcfdf26daf16e67f350da26617/src/NewUser.js#L31-L51

All these info logged using `console.log` (40-43) seems correct to me — I verified it using React Native Debugger:

![image](https://user-images.githubusercontent.com/14119096/37673236-77527bf6-2c4e-11e8-83b2-44b47e709876.png)

I use it to make a connection with my client-side store and append a new edge using `insertEdgeAfter`, therefore I should view the new user in the [UserList](https://github.com/julioxavierr/entria-challenge/blob/master/src/scenes/UserList.js) scene. However, I get this error:

<img src="https://user-images.githubusercontent.com/14119096/37672643-2bc94c4c-2c4d-11e8-897d-7c5e8e249011.png" width="187" height="340" />

**Comment by jgcmarins** [comment]
could you provide more details/logs about error?

**Comment by julioxavierr** [comment]
@jgcmarins description updated.

**Comment by jgcmarins** [comment]
Well, erro is located on `UserList.js` at line 25.
https://github.com/julioxavierr/entria-challenge/blob/master/src/scenes/UserList.js#L25
id is `null` or `undefined`.
